server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wallet_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Tạo bảng nếu chưa có hoặc cập nhật bảng đã tồn tại
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
    level:
      root: INFO
      org.springframework: INFO
      org.hibernate: INFO
      org.springframework.web: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"


infura:
  url: https://mainnet.infura.io/v3/25657cb97d2a48b9a24f8e3910b2cfff


